name: slack_notification
on:
  push:
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
          echo "Installing Salesforce CLI..."
          npm install -g @salesforce/cli
      - name: SFCA installation
        run: |
          echo "Installing SFCA..."
          echo "y" | sf plugins install @salesforce/plugin-code-analyzer

      - name: Analyzer Run
        run: |
          echo "Running SFCA..."
          sf code-analyzer run --target force-app --rule-selector all --severity-threshold 2 --view=detail --output-file sfca-result.json --output-file sfca-result.sarif     
          
      - name: upload-result
        uses: actions/upload-artifact@v4
        id: upload-result
        with:
          name: sfca-result
          path: sfca-result.json

      - name: Send Slack Notification
        run: |

          url=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
          artifact_url=$(echo $url | jq -r '.artifacts[0].archive_download_url')  
          echo $artifact_url
          MESSAGE="🔍 SFCA Scan Completed
          📊 Violations: 30
          📁 Artifact: sfca-report
          🔗 View here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo $MESSAGE
          # CONTENT=$(cat sfca-result.json | sed ':a;N;$!ba;s/\n/\\n/g')
          # curl -X POST -H "Content-type: application/json" \
          # --data "{\"text\":\"$CONTENT\"}" \
          # ${{ secrets.SLACK_WEBHOOK_URL }}